import { ShaderGradient, ShaderGradientCanvas } from "@shadergradient/react";

const canvasStyle = {
  position: "fixed",
  inset: 0,
  zIndex: -10,
  pointerEvents: "none",
};

const configs = {
  work: {
    animate: "on",
    axesHelper: "off",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 0.8,
    cAzimuthAngle: -130,
    cDistance: 0.5,
    cPolarAngle: 150,
    cameraZoom: 13.9,
    color1: "#73bfc4",
    color2: "#ff810a",
    color3: "#8da0ce",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 40,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "on",
    lightType: "env",
    pixelDensity: 3,
    positionX: 0.5,
    positionY: 0,
    positionZ: 0,
    range: "enabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.4,
    rotationX: 0,
    rotationY: 130,
    rotationZ: 70,
    shader: "defaults",
    type: "sphere",
    uAmplitude: 0,
    uDensity: 2.6,
    uFrequency: 5.5,
    uSpeed: 0.1,
    uStrength: 0.8,
    uTime: 0,
    wireframe: false,
  },
  personal: {
    animate: "on",
    axesHelper: "off",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1.2,
    cAzimuthAngle: 180,
    cDistance: 2.9,
    cPolarAngle: 120,
    cameraZoom: 1,
    color1: "#ebedff",
    color2: "#f3f2f8",
    color3: "#dbf8ff",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "off",
    lightType: "3d",
    pixelDensity: 1,
    positionX: 0,
    positionY: 1.8,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -90,
    shader: "defaults",
    type: "waterPlane",
    uAmplitude: 0,
    uDensity: 1,
    uFrequency: 5.5,
    uSpeed: 0.3,
    uStrength: 3,
    uTime: 0.2,
    wireframe: false,
  },
};

export default function ShaderBackground({ mode }) {
  return (
    <ShaderGradientCanvas key={mode} style={canvasStyle}>
      <ShaderGradient control="props" {...configs[mode]} />
    </ShaderGradientCanvas>
  );
}
