import { ShaderGradient, ShaderGradientCanvas } from "@shadergradient/react";

const canvasStyle = {
  position: "fixed",
  inset: 0,
  zIndex: -10,
  pointerEvents: "none",
};

const configs = {
  work: {
    animate: "on",
    axesHelper: "off",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1,
    cAzimuthAngle: 180,
    cDistance: 2.8,
    cPolarAngle: 80,
    cameraZoom: 9.1,
    color1: "#606080",
    color2: "#8d7dca",
    color3: "#212121",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "on",
    lightType: "3d",
    pixelDensity: 1,
    positionX: 0,
    positionY: 0,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 50,
    rotationY: 0,
    rotationZ: -60,
    shader: "defaults",
    type: "waterPlane",
    uAmplitude: 0,
    uDensity: 1.5,
    uFrequency: 0,
    uSpeed: 0.3,
    uStrength: 1.5,
    uTime: 8,
    wireframe: false,
  },
  personal: {
    animate: "on",
    axesHelper: "off",
    bgColor1: "#000000",
    bgColor2: "#000000",
    brightness: 1.2,
    cAzimuthAngle: 180,
    cDistance: 2.9,
    cPolarAngle: 120,
    cameraZoom: 1,
    color1: "#ebedff",
    color2: "#f3f2f8",
    color3: "#dbf8ff",
    destination: "onCanvas",
    embedMode: "off",
    envPreset: "city",
    format: "gif",
    fov: 45,
    frameRate: 10,
    gizmoHelper: "hide",
    grain: "off",
    lightType: "3d",
    pixelDensity: 1,
    positionX: 0,
    positionY: 1.8,
    positionZ: 0,
    range: "disabled",
    rangeEnd: 40,
    rangeStart: 0,
    reflection: 0.1,
    rotationX: 0,
    rotationY: 0,
    rotationZ: -90,
    shader: "defaults",
    type: "waterPlane",
    uAmplitude: 0,
    uDensity: 1,
    uFrequency: 5.5,
    uSpeed: 0.3,
    uStrength: 3,
    uTime: 0.2,
    wireframe: false,
  },
};

export default function ShaderBackground({ mode }) {
  return (
    <ShaderGradientCanvas key={mode} style={canvasStyle}>
      <ShaderGradient control="props" {...configs[mode]} />
    </ShaderGradientCanvas>
  );
}
